site_name: Bernardo Galvão's MLOps blog
site_url: https://bgalvao.github.io

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - header.autohide
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    -
    - search
    - search.suggest
    - search.highlight
    - search.share

  font:
    text: Fira Sans
    code: Ubuntu Mono

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bgalvao
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/bcgalvao
